export type SinaleArticle = {
  slug: string
  title: string
  description: string
  category: string
  audience: string
  tool: string
  angle: string
  outcome: string
  steps: string[]
  pitfalls: string[]
}

const articleSeeds = [
  ["ai-tool-audit", "How to Run an AI Tool Audit Before Your Stack Gets Messy", "Operations", "founders and team leads", "a shared spreadsheet", "Too many AI tools create hidden cost, duplicated workflows, and unclear ownership.", "a smaller stack that people actually use", ["List every paid AI tool", "Map each tool to a real workflow", "Mark owners and renewal dates", "Cut tools with no weekly use"], ["Tracking features instead of outcomes", "Keeping overlapping tools because someone might use them later"]],
  ["chatgpt-writing-system", "A Simple ChatGPT Writing System for Better Drafts", "Writing", "founders and marketers", "ChatGPT", "Better AI writing starts with context, examples, and a clear editing pass.", "drafts that sound intentional instead of generic", ["Give the audience and goal", "Paste a strong reference sample", "Ask for three outline options", "Edit the final draft manually"], ["Letting the first draft become the final", "Asking for polish before the argument is clear"]],
  ["claude-research-workflow", "How I Use Claude to Turn Research Notes Into Decisions", "Research", "product managers", "Claude", "Research only matters when it changes a decision.", "clear recommendations from messy notes", ["Collect raw notes", "Group evidence by theme", "Ask for decision options", "Pressure-test assumptions"], ["Summarizing too early", "Ignoring contradictory evidence"]],
  ["cursor-refactor-checklist", "A Cursor Refactoring Checklist for Small Teams", "Development", "developers", "Cursor", "AI refactors are fastest when the scope is narrow and the tests are obvious.", "cleaner code without surprise rewrites", ["Describe the exact smell", "Limit files before editing", "Ask for a plan first", "Run tests after each change"], ["Accepting large edits blindly", "Mixing refactor and feature work"]],
  ["perplexity-source-checking", "How to Use Perplexity Without Fooling Yourself", "Research", "analysts and founders", "Perplexity", "Fast answers still need source judgment.", "research you can trust enough to act on", ["Start with a specific question", "Open the cited sources", "Compare dates and incentives", "Save only decision-relevant facts"], ["Treating citations as proof", "Mixing old market data with current claims"]],
  ["granola-customer-interviews", "Using Granola for Cleaner Customer Interview Notes", "Customer Research", "product teams", "Granola", "The best interview notes preserve language, emotion, and context.", "better synthesis after customer calls", ["Set an interview goal", "Capture verbatim phrases", "Tag pains and triggers", "Write the follow-up while context is fresh"], ["Over-summarizing customer words", "Skipping the interviewer recap"]],
  ["lovable-mvp-scope", "How to Scope a Lovable MVP Without Building Too Much", "MVPs", "founders", "Lovable", "AI app builders reward sharp product boundaries.", "a smaller prototype that can be tested quickly", ["Define one user", "Choose one core job", "Skip admin polish", "Ship the narrow flow first"], ["Prompting a full SaaS too early", "Confusing demo completeness with product validation"]],
  ["replit-demo-apps", "When Replit Is the Right Place to Build a Demo App", "Development", "students and founders", "Replit", "Browser-based development is useful when speed and sharing matter more than local control.", "a working demo people can try", ["Start from a simple template", "Keep dependencies minimal", "Use secrets carefully", "Share the running app"], ["Treating demos as production systems", "Ignoring environment configuration"]],
  ["notion-ai-team-knowledge", "Using Notion AI to Clean Up Team Knowledge", "Knowledge Work", "operators and PMs", "Notion AI", "A messy workspace makes every AI answer worse.", "a knowledge base people can navigate", ["Archive stale pages", "Create canonical docs", "Summarize long histories", "Add owners to key pages"], ["Automating before organizing", "Keeping duplicate sources of truth"]],
  ["meeting-assistant-rubric", "A Practical Rubric for Choosing an AI Meeting Assistant", "Meetings", "managers", "AI meeting assistants", "The best meeting tool depends on what happens after the call.", "meeting notes that turn into action", ["Compare capture quality", "Test summaries on real calls", "Review privacy settings", "Check integrations"], ["Picking only by transcript accuracy", "Ignoring participant consent"]],
  ["ai-code-review", "How to Use AI for Code Review Without Lowering Standards", "Development", "engineering teams", "Claude or Cursor", "AI can widen review coverage, but humans still own judgment.", "faster reviews with fewer missed issues", ["Ask for risk areas", "Review diffs in small chunks", "Check tests and edge cases", "Make the final call yourself"], ["Letting AI approve changes", "Skipping domain-specific behavior"]],
  ["product-discovery-ai", "A Lightweight AI Workflow for Product Discovery", "Product", "product managers", "Claude and Perplexity", "Discovery improves when synthesis and evidence stay connected.", "clearer bets before writing specs", ["Collect customer inputs", "Find market context", "Cluster opportunities", "Write a decision memo"], ["Mistaking volume of notes for insight", "Researching after the decision is made"]],
  ["ai-design-critique", "How Designers Can Use AI for Sharper Critiques", "Design", "product designers", "ChatGPT or Claude", "AI critique is useful when it evaluates against goals instead of taste.", "more specific design feedback", ["State the user goal", "Describe the screen context", "Ask for usability risks", "Decide what to ignore"], ["Accepting generic visual advice", "Skipping real user feedback"]],
  ["ux-research-synthesis", "Turning UX Research Into Themes With AI", "Research", "UX researchers", "Claude", "AI can accelerate synthesis when raw evidence stays visible.", "themes that remain grounded in interviews", ["Paste notes by participant", "Extract repeated pains", "Separate facts from interpretation", "Pull representative quotes"], ["Flattening minority signals", "Letting the model invent certainty"]],
  ["data-analysis-prompts", "Prompts That Make AI Data Analysis More Useful", "Analytics", "analysts", "ChatGPT", "Data prompts work best when they include schema, question, and decision context.", "analysis that answers the business question", ["Share column definitions", "Explain the metric", "Ask for possible confounders", "Validate with queries"], ["Uploading unclear data", "Trusting charts without checking logic"]],
  ["dashboard-narratives", "How to Write Better Dashboard Narratives With AI", "Analytics", "data teams", "Claude", "A dashboard needs a story, not just numbers.", "clearer takeaways for stakeholders", ["Identify the decision", "Explain metric movement", "Name likely drivers", "Add next actions"], ["Restating every chart", "Hiding uncertainty"]],
  ["founder-landing-page-ai", "Using AI to Draft a Founder Landing Page", "Marketing", "founders", "ChatGPT", "A good landing page explains the customer pain before the product features.", "a sharper first version of your page", ["Define the target buyer", "Write the problem section", "Draft proof points", "Tighten the CTA"], ["Starting with clever headlines", "Listing features without stakes"]],
  ["saas-onboarding-ai", "AI Prompts for Improving SaaS Onboarding", "Product", "growth teams", "Claude", "Onboarding should reduce confusion, not show everything.", "a simpler first-run experience", ["Map the activation moment", "Find confusing steps", "Rewrite empty states", "Test one shorter flow"], ["Adding more tooltips by default", "Optimizing before measuring drop-off"]],
  ["support-macro-ai", "How to Build Better Support Macros With AI", "Support", "support teams", "ChatGPT", "Support macros should sound helpful while staying accurate.", "faster replies that still feel human", ["Collect common tickets", "Write answer rules", "Create tone examples", "Review for policy accuracy"], ["Over-automating sensitive replies", "Using vague promises"]],
  ["sales-prospecting-ai", "An AI-Assisted Sales Prospecting Workflow That Does Not Feel Lazy", "Sales", "founders and sales teams", "Perplexity and ChatGPT", "Good prospecting depends on relevance, not volume.", "more specific outreach lists", ["Define ideal accounts", "Research trigger events", "Write a tailored angle", "Track what converts"], ["Personalization theater", "Scraping lists without qualification"]],
  ["email-sequence-ai", "How to Draft Better Email Sequences With AI", "Marketing", "founders", "ChatGPT", "Email sequences need a progression, not five versions of the same pitch.", "emails with clearer purpose", ["Define the reader stage", "Write one job per email", "Add proof gradually", "Remove filler"], ["Using hype words", "Sending before checking deliverability basics"]],
  ["docs-with-ai", "Using AI to Write Product Documentation Faster", "Documentation", "developers and PMs", "Claude", "Documentation improves when AI starts from real behavior.", "docs that answer user questions", ["Describe the workflow", "Add setup requirements", "Include failure states", "Review with the product open"], ["Documenting imagined features", "Skipping screenshots or examples"]],
  ["changelog-ai", "A Better Changelog Workflow With AI", "Product", "product teams", "Claude", "A changelog should explain why users should care.", "release notes people understand", ["Collect merged changes", "Group by user impact", "Rewrite technical language", "Link to docs"], ["Publishing commit summaries", "Overstating small fixes"]],
  ["pricing-page-ai", "How to Use AI to Improve a Pricing Page", "Marketing", "founders", "ChatGPT", "Pricing pages should reduce decision anxiety.", "clearer packaging and plan copy", ["List buyer segments", "Name plan differences", "Clarify limits", "Rewrite FAQs"], ["Hiding important constraints", "Copying competitor packaging blindly"]],
  ["competitor-research-ai", "A Founder-Friendly Competitor Research Workflow", "Research", "founders", "Perplexity", "Competitor research should inform positioning, not create fear.", "a clearer view of market gaps", ["List direct alternatives", "Compare jobs served", "Read customer complaints", "Summarize positioning angles"], ["Tracking every competitor forever", "Ignoring switching costs"]],
  ["content-calendar-ai", "Building a Useful Content Calendar With AI", "Content", "solo creators", "ChatGPT", "A calendar is only useful if it matches your actual publishing capacity.", "a realistic content plan", ["Choose core topics", "Map buyer questions", "Batch related posts", "Leave room for updates"], ["Planning more than you can ship", "Writing for keywords alone"]],
  ["seo-briefs-ai", "How to Create SEO Briefs With AI Without Producing Generic Content", "SEO", "content teams", "Perplexity and Claude", "A useful brief combines search intent with original perspective.", "briefs that guide stronger articles", ["Study the SERP", "Identify missing angles", "Define reader outcome", "Add internal links"], ["Copying competitor outlines", "Ignoring expertise and examples"]],
  ["voice-of-customer-ai", "Turning Customer Feedback Into Voice-of-Customer Insights", "Research", "growth teams", "Claude", "Customer language reveals positioning that internal teams miss.", "copy and roadmap inputs from real feedback", ["Collect reviews and tickets", "Cluster phrases", "Separate pain from feature requests", "Extract exact wording"], ["Treating loud users as everyone", "Cleaning up language too much"]],
  ["pm-spec-ai", "How Product Managers Can Draft Better Specs With AI", "Product", "product managers", "Claude", "AI helps specs when it exposes ambiguity early.", "clearer requirements before engineering starts", ["Write the problem", "Define success metrics", "Generate edge cases", "Ask engineering for review"], ["Letting the spec become too long", "Skipping tradeoffs"]],
  ["roadmap-ai", "Using AI to Pressure-Test a Roadmap", "Strategy", "product leaders", "Claude", "A roadmap needs assumptions, risks, and sequencing logic.", "a roadmap that survives harder questions", ["List themes", "Name assumptions", "Score confidence", "Cut low-evidence work"], ["Treating AI scores as truth", "Optimizing for internal politics"]],
  ["bug-triage-ai", "A Simple AI Workflow for Bug Triage", "Development", "support and engineering teams", "ChatGPT", "Bug triage improves when reports become reproducible cases.", "cleaner handoffs to engineering", ["Summarize the report", "Extract reproduction steps", "Identify missing info", "Draft the ticket"], ["Inventing root causes", "Skipping logs and screenshots"]],
  ["analytics-qa-ai", "How to QA Analytics Events With AI", "Analytics", "growth teams", "Claude", "Analytics QA is about naming, coverage, and consistency.", "cleaner product data", ["List critical events", "Check naming patterns", "Compare expected properties", "Review gaps after launch"], ["Tracking everything", "Changing event names casually"]],
  ["data-dictionary-ai", "Using AI to Build a Data Dictionary People Actually Use", "Analytics", "data teams", "ChatGPT", "Definitions reduce confusion only when they are short and discoverable.", "shared metric understanding", ["Collect common metrics", "Define source tables", "Add owners", "Include examples"], ["Writing academic definitions", "Letting definitions drift"]],
  ["onboarding-docs-ai", "How to Create Better Employee Onboarding Docs With AI", "Operations", "small teams", "Claude", "Onboarding docs should help someone become useful quickly.", "faster ramp for new teammates", ["List first-week tasks", "Explain team rituals", "Link core systems", "Add common questions"], ["Documenting everything at once", "Forgetting ownership"]],
  ["investor-update-ai", "A Practical AI Workflow for Investor Updates", "Founders", "founders", "Claude", "Investor updates should be honest, concise, and decision-oriented.", "updates that build trust", ["Gather metrics", "Explain wins and misses", "Name asks", "Keep a consistent format"], ["Over-polishing bad news", "Including too many vanity metrics"]],
  ["workflow-automation-ai", "How to Find Automation Opportunities With AI", "Operations", "operators", "ChatGPT", "The best automations remove repeated decisions, not just repeated clicks.", "a prioritized automation backlog", ["List recurring tasks", "Estimate frequency", "Find handoff pain", "Start with low-risk workflows"], ["Automating broken processes", "Ignoring exceptions"]],
  ["no-code-ai-ops", "Combining No-Code Tools and AI for Lean Operations", "Operations", "founders", "Zapier and AI tools", "Lean operations work when simple systems stay understandable.", "fewer manual handoffs", ["Choose one workflow", "Define inputs and outputs", "Add human review", "Monitor failures"], ["Building brittle chains", "Skipping documentation"]],
  ["ai-privacy-checklist", "A Practical Privacy Checklist for AI Tool Adoption", "Operations", "team leads", "vendor settings", "AI adoption needs basic data boundaries.", "safer tool rollout", ["Classify sensitive data", "Review retention settings", "Limit workspace access", "Document approved use"], ["Assuming defaults are safe", "Letting every team choose alone"]],
  ["ai-evaluation-scorecard", "An AI Tool Evaluation Scorecard for Teams", "Strategy", "operators and buyers", "a scorecard", "A scorecard helps teams compare tools on fit instead of hype.", "better buying decisions", ["Define use cases", "Score workflow fit", "Test with real tasks", "Review cost and risk"], ["Testing with toy prompts", "Overweighting demos"]],
  ["model-comparison-workflow", "How to Compare AI Models for Real Work", "AI Strategy", "builders", "ChatGPT, Claude, and Gemini", "Model comparisons only matter when tied to repeated tasks.", "a practical model choice", ["Pick three real tasks", "Use the same context", "Score outputs blindly", "Measure editing time"], ["Comparing vibes", "Ignoring latency and cost"]],
  ["human-review-loop", "Designing Human Review Loops for AI Workflows", "AI Strategy", "team leads", "review checklists", "AI workflows need clear points where humans verify quality.", "safer automation", ["Identify risk points", "Define reviewer responsibility", "Create acceptance criteria", "Track recurring failures"], ["Reviewing everything manually", "Leaving accountability vague"]],
  ["team-ai-policy", "A Small-Team AI Policy You Can Actually Use", "Operations", "founders and managers", "a shared policy doc", "A useful AI policy is short, specific, and easy to follow.", "clear rules without slowing people down", ["Name approved tools", "Define sensitive data", "Explain review expectations", "Set update cadence"], ["Writing legalistic docs nobody reads", "Ignoring real workflows"]],
  ["prompt-handoffs", "How to Hand Off Prompts Between Teammates", "Collaboration", "product teams", "shared prompt docs", "Prompts become more useful when they include context and examples.", "repeatable AI workflows", ["Save the goal", "Include inputs", "Show a good output", "Document when not to use it"], ["Saving clever prompts without context", "Letting prompt libraries rot"]],
  ["knowledge-base-cleanup", "Cleaning a Knowledge Base Before Adding AI Search", "Knowledge Work", "ops teams", "Notion or docs tools", "AI search cannot rescue a messy source of truth.", "better answers from internal AI", ["Remove stale pages", "Merge duplicates", "Add owners", "Standardize titles"], ["Buying search before cleanup", "Keeping conflicting docs"]],
  ["agent-task-design", "How to Design Tasks for AI Agents", "AI Agents", "developers and operators", "AI agents", "Agents work best on bounded tasks with observable outcomes.", "more reliable agent runs", ["Define the finish line", "Limit permissions", "Give examples", "Review logs"], ["Asking agents to own strategy", "Giving broad access too early"]],
  ["github-discussions-content", "Using GitHub Discussions as a Lightweight Community Layer", "Community", "developer-focused founders", "GitHub Discussions", "GitHub Discussions can support early community without a separate platform.", "a simple place for public product conversations", ["Create clear categories", "Seed useful topics", "Link from content", "Moderate weekly"], ["Expecting community to appear automatically", "Creating too many categories"]],
  ["comments-on-content-sites", "Should Content Sites Add Comments Again?", "Content", "creators", "Giscus", "Comments are useful when they create feedback loops, not just noise.", "a clearer decision about discussion features", ["Define why comments matter", "Choose moderation rules", "Start on key articles", "Review signal quality"], ["Adding comments for vanity", "Ignoring spam and moderation"]],
  ["launch-checklist-ai", "An AI-Assisted Launch Checklist for Side Projects", "Launch", "indie builders", "Claude", "Launches go better when the boring pieces are visible.", "a calmer release day", ["Check core flows", "Review copy", "Prepare support replies", "Write the launch post"], ["Polishing forever", "Skipping rollback plans"]],
  ["ai-stack-budget", "How to Set a Realistic AI Tool Budget", "Operations", "founders", "a budget tracker", "AI tool budgets need ownership and renewal discipline.", "less subscription sprawl", ["List active seats", "Group by workflow", "Set monthly caps", "Review usage quarterly"], ["Buying per-person tools without owners", "Ignoring annual renewals"]],
  ["browser-research-workflow", "A Browser-Based AI Research Workflow for Faster Decisions", "Research", "busy builders", "Perplexity and ChatGPT", "Browser research works best when discovery, verification, and synthesis are separate steps.", "faster decisions with fewer unsupported claims", ["Search for current sources", "Open the strongest references", "Summarize only verified points", "Write the decision separately"], ["Confusing search snippets with evidence", "Letting synthesis happen before verification"]],
] as const

export const articles: SinaleArticle[] = articleSeeds.map(
  ([
    slug,
    title,
    category,
    audience,
    tool,
    angle,
    outcome,
    steps,
    pitfalls,
  ]) => ({
    slug,
    title,
    category,
    audience,
    tool,
    angle,
    outcome,
    steps: [...steps],
    pitfalls: [...pitfalls],
    description: `${angle} This guide helps ${audience} get to ${outcome}.`,
  }),
)

export function getArticle(slug: string) {
  return articles.find((article) => article.slug === slug)
}
