const toolDomainOverrides: Record<string, string> = {
  "11x": "11x.ai",
  "15five-ai": "15five.com",
  "activecampaign-ai": "activecampaign.com",
  "adobe-firefly": "adobe.com",
  "adobe-podcast": "adobe.com",
  "ahrefs-ai": "ahrefs.com",
  "airfocus-ai": "airfocus.com",
  "albert-ai": "albert.ai",
  "algolia-ai": "algolia.com",
  "amplitude-ai": "amplitude.com",
  "apollo": "apollo.io",
  "artisan": "artisan.co",
  "autogen": "microsoft.com",
  "beautiful-ai": "beautiful.ai",
  "bolt": "bolt.new",
  "brave-leo": "brave.com",
  "brevo-ai": "brevo.com",
  "buffer-ai": "buffer.com",
  "builder-io": "builder.io",
  "canva-ai": "canva.com",
  "captions": "captions.ai",
  "chatgpt": "openai.com",
  "claude": "anthropic.com",
  "claude-code": "anthropic.com",
  "clay": "clay.com",
  "clearscope": "clearscope.io",
  "codeium": "windsurf.com",
  "common-room": "commonroom.io",
  "content-shake-ai": "semrush.com",
  "copy-ai": "copy.ai",
  "crowdstrike-charlotte": "crowdstrike.com",
  "cursor": "cursor.com",
  "customer-io-ai": "customer.io",
  "d-id": "d-id.com",
  "dataiku": "dataiku.com",
  "datarobot": "datarobot.com",
  "deel-ai": "deel.com",
  "decktopus": "decktopus.com",
  "deepbrain-ai": "deepbrain.io",
  "designs-ai": "designs.ai",
  "drata-ai": "drata.com",
  "duolingo-max": "duolingo.com",
  "eesel-ai": "eesel.ai",
  "elevenlabs": "elevenlabs.io",
  "exa": "exa.ai",
  "figma-ai": "figma.com",
  "fireflies": "fireflies.ai",
  "flutterflow-ai": "flutterflow.io",
  "framer-ai": "framer.com",
  "freepik-ai": "freepik.com",
  "freshdesk-ai": "freshdesk.com",
  "gamma": "gamma.app",
  "gemini": "gemini.google.com",
  "github-copilot": "github.com",
  "gladly-sidekick": "gladly.com",
  "gong": "gong.io",
  "google": "google.com",
  "gorgias-ai": "gorgias.com",
  "granola": "granola.ai",
  "grammarly": "grammarly.com",
  "gusto-ai": "gusto.com",
  "h2o-ai": "h2o.ai",
  "helpscout-ai": "helpscout.com",
  "help-scout-ai": "helpscout.com",
  "heygen": "heygen.com",
  "hootsuite-owlywriter": "hootsuite.com",
  "hubspot-ai": "hubspot.com",
  "invideo-ai": "invideo.io",
  "instant-ai": "instantly.ai",
  "instantly-ai": "instantly.ai",
  "intercom-fin": "intercom.com",
  "jasper": "jasper.ai",
  "klaviyo-ai": "klaviyo.com",
  "klenty-ai": "klenty.com",
  "krisp": "krisp.ai",
  "kustomer-ai": "kustomer.com",
  "langchain": "langchain.com",
  "langgraph": "langchain.com",
  "langsmith": "langchain.com",
  "later-ai": "later.com",
  "lavender": "lavender.ai",
  "lemlist-ai": "lemlist.com",
  "linear-ai": "linear.app",
  "litmaps": "litmaps.com",
  "lovable": "lovable.dev",
  "luma": "lumalabs.ai",
  "lyssna-ai": "lyssna.com",
  "mailchimp-ai": "mailchimp.com",
  "make": "make.com",
  "marketmuse": "marketmuse.com",
  "mentimeter-ai": "mentimeter.com",
  "microsoft": "microsoft.com",
  "midjourney": "midjourney.com",
  "mixpanel-ai": "mixpanel.com",
  "notion-ai": "notion.com",
  "notebooklm": "notebooklm.google.com",
  "octane-ai": "octaneai.com",
  "openai-gpts": "openai.com",
  "opus-clip": "opus.pro",
  "outreach-ai": "outreach.io",
  "pageoptimizer-pro": "pageoptimizer.pro",
  "perplexity": "perplexity.ai",
  "play-ht": "play.ht",
  "plus-ai": "plusdocs.com",
  "power-bi-copilot": "microsoft.com",
  "presentations-ai": "presentations.ai",
  "productboard-ai": "productboard.com",
  "quizlet-ai": "quizlet.com",
  "read-ai": "read.ai",
  "regie": "regie.ai",
  "regie-ai": "regie.ai",
  "relay": "relay.app",
  "relay-app": "relay.app",
  "relevance-ai": "relevanceai.com",
  "reply-io-ai": "reply.io",
  "replit-agent": "replit.com",
  "research-rabbit": "researchrabbit.ai",
  "rippling-ai": "rippling.com",
  "salesloft-ai": "salesloft.com",
  "semrush-ai": "semrush.com",
  "semantic-scholar": "semanticscholar.org",
  "sentry": "sentry.io",
  "shopify-magic": "shopify.com",
  "shopify-sidekick": "shopify.com",
  "sierra": "sierra.ai",
  "sigma-ai": "sigmacomputing.com",
  "slidesai": "slidesai.io",
  "smartlead": "smartlead.ai",
  "sourcegraph-cody": "sourcegraph.com",
  "sprout-ai": "sproutsocial.com",
  "stable-assistant": "stability.ai",
  "surfer-ai": "surferseo.com",
  "surfer-seo": "surferseo.com",
  "tableau-agent": "tableau.com",
  "tableau-pulse": "tableau.com",
  "tl-dv": "tldv.io",
  "topaz-photo-ai": "topazlabs.com",
  "unbounce-smart-copy": "unbounce.com",
  "usertesting-ai": "usertesting.com",
  "uservoice-ai": "uservoice.com",
  "v0": "v0.dev",
  "veed-ai": "veed.io",
  "veo": "deepmind.google",
  "wordvice-ai": "wordvice.ai",
  "workable-ai": "workable.com",
  "workday-ai": "workday.com",
  "you-com": "you.com",
  "zapier-ai": "zapier.com",
  "zendesk-ai": "zendesk.com",
  "zoho-show-ai": "zoho.com",
}

export function getToolDomain(name: string) {
  const slug = name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")

  return Object.hasOwn(toolDomainOverrides, slug)
    ? toolDomainOverrides[slug]
    : `${slug}.com`
}

export function getLogoDevUrl(domain: string) {
  const params = new URLSearchParams({
    size: "64",
    format: "png",
    fallback: "404",
  })
  const token =
    process.env.NEXT_PUBLIC_LOGO_DEV_TOKEN ??
    process.env.NEXT_PUBLIC_LOGO_DEV_KEY

  if (token) {
    params.set("token", token)
  }

  return `https://img.logo.dev/${domain}?${params.toString()}`
}
